import React, { useState } from 'react';
import { LogOut, Brain, Shield, Zap, Upload, Search, MessageSquare, FileText, Activity } from 'lucide-react';
import MedicalLogo from './MedicalLogo';
import { User } from '../App';
import Modal from './Modal';
import ThemeToggle from './ThemeToggle';
import InteractiveTutorial from './InteractiveTutorial';
import WelcomeModal from './WelcomeModal';

interface HomePageProps {
  user: User;
  onLogout: () => void;
  onNavigateToChatbot: (context: 'upload' | 'medicine-search' | 'question') => void;
}

interface Answer {
  id: string;
  question: string;
  response: string;
  timestamp: Date;
}

const HomePage: React.FC<HomePageProps> = ({ user, onLogout, onNavigateToChatbot }) => {
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalType, setModalType] = useState<'upload' | 'medicine-search' | 'question'>('upload');
  const [modalTitle, setModalTitle] = useState('');
  const [showTutorial, setShowTutorial] = useState(true);
  const [showWelcomeModal, setShowWelcomeModal] = useState(true);
  const [welcomeSkipped, setWelcomeSkipped] = useState(false);

  const handleFeatureClick = (feature: string) => {
    if (feature === 'upload') {
      setModalType('upload');
      setModalTitle('Upload Your Doctor\'s Prescription');
      setModalOpen(true);
    } else if (feature === 'medicine-search') {
      onNavigateToChatbot('medicine-search');
    } else if (feature === 'question') {
      onNavigateToChatbot('question');
    }
  };

  const handleAddAnswer = (question: string) => {
    const newAnswer: Answer = {
      id: Date.now().toString(),
      question,
      response: 'This is a sample response to your question. In a real application, this would be generated by an AI system.',
      timestamp: new Date()
    };
    setAnswers(prev => [newAnswer, ...prev]);
    setModalOpen(false);
  };

  const handleTutorialComplete = () => {
    setShowTutorial(false);
    localStorage.setItem('medilens-tutorial-completed', 'true');
  };

  const handleTutorialSkip = () => {
    setShowTutorial(false);
    localStorage.setItem('medilens-tutorial-completed', 'true');
  };

  const handleWelcomeClose = () => {
    setShowWelcomeModal(false);
  };

  const handleWelcomeSkip = () => {
    setShowWelcomeModal(false);
    setWelcomeSkipped(true);
    sessionStorage.setItem('medilens-welcome-skipped', 'true');
  };

  // Check if tutorial was previously completed
  React.useEffect(() => {
    const tutorialCompleted = localStorage.getItem('medilens-tutorial-completed');
    const welcomeSkippedSession = sessionStorage.getItem('medilens-welcome-skipped');
    
    if (tutorialCompleted === 'true') {
      setShowTutorial(false);
    }
    
    if (welcomeSkippedSession === 'true') {
      setShowWelcomeModal(false);
      setWelcomeSkipped(true);
    }
  }, []);

  return (
    <div className="home-page">
      {/* Header */}
      <div className="header bg-[var(--glass-bg)] backdrop-blur-[30px] border-b border-[var(--glass-border)] p-[20px_40px] flex justify-between items-center sticky top-0 z-[100]">
        <div className="header-left flex items-center gap-4">
          <MedicalLogo size={50} />
          <h1 className="header-title font-['Orbitron'] text-[var(--text-primary)] text-2xl font-semibold">
            MediLens
          </h1>
        </div>
        <div id="user-profile-section" className="header-right flex items-center gap-4">
          <div className="user-info text-[var(--text-secondary)] text-sm">
            Welcome, {user.name}
          </div>
          <ThemeToggle />
          <button
            onClick={onLogout}
            className="logout-btn p-[8px_16px] bg-[rgba(255,255,255,0.1)] border border-[var(--glass-border)] rounded-lg text-[var(--text-secondary)] cursor-pointer transition-all duration-200 hover:bg-[rgba(255,255,255,0.15)] hover:text-[var(--text-primary)]"
          >
            <LogOut className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="main-content p-10 max-w-[1200px] mx-auto">
        <div className="welcome-section text-center mb-[50px]">
          <h1 className="welcome-title font-['Orbitron'] text-[2.5rem] font-semibold text-[var(--text-primary)] mb-3">
            Healthcare AI Dashboard
          </h1>
          <p className="welcome-subtitle text-[var(--text-secondary)] text-lg max-w-[600px] mx-auto">
            Leverage advanced AI technology to enhance patient care and medical decision-making
          </p>
        </div>

        {/* Feature Cards */}
        <div className="features-grid grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] gap-8 mb-[50px]">
          <div
            id="prescription-upload-button"
            className="feature-card bg-[var(--glass-bg)] backdrop-blur-[20px] border border-[var(--glass-border)] rounded-[20px] p-8 text-center transition-all duration-300 cubic-bezier-[0.4,0,0.2,1] cursor-pointer relative overflow-hidden hover:transform hover:-translate-y-2 hover:border-[var(--primary-cyan)] hover:shadow-[0_25px_50px_rgba(0,212,170,0.2)] before:content-[''] before:absolute before:top-0 before:-left-full before:w-full before:h-full before:bg-gradient-to-r before:from-transparent before:via-[rgba(0,212,170,0.1)] before:to-transparent before:transition-[left_0.6s_ease] hover:before:left-full"
            onClick={() => handleFeatureClick('upload')}
          >
            <div className="feature-icon w-[60px] h-[60px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] rounded-2xl flex items-center justify-center mx-auto mb-5 text-[28px]">
              <Upload className="w-7 h-7 text-white" />
            </div>
            <h3 className="feature-title font-['Orbitron'] text-xl font-semibold text-[var(--text-primary)] mb-3">
              Upload Your Doctor's Prescription
            </h3>
            <p className="feature-description text-[var(--text-secondary)] leading-[1.6] mb-5">
              Securely upload your doctor's prescription and get AI-powered insights and analysis
            </p>
            <button className="feature-button p-[12px_24px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] text-white border-none rounded-[10px] font-semibold cursor-pointer transition-all duration-200 hover:transform hover:-translate-y-[2px] hover:shadow-[0_8px_20px_rgba(0,212,170,0.3)]">
              Start Analysis
            </button>
          </div>

          <div
            id="medicine-search-button"
            className="feature-card bg-[var(--glass-bg)] backdrop-blur-[20px] border border-[var(--glass-border)] rounded-[20px] p-8 text-center transition-all duration-300 cubic-bezier-[0.4,0,0.2,1] cursor-pointer relative overflow-hidden hover:transform hover:-translate-y-2 hover:border-[var(--primary-cyan)] hover:shadow-[0_25px_50px_rgba(0,212,170,0.2)] before:content-[''] before:absolute before:top-0 before:-left-full before:w-full before:h-full before:bg-gradient-to-r before:from-transparent before:via-[rgba(0,212,170,0.1)] before:to-transparent before:transition-[left_0.6s_ease] hover:before:left-full"
            onClick={() => handleFeatureClick('medicine-search')}
          >
            <div className="feature-icon w-[60px] h-[60px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] rounded-2xl flex items-center justify-center mx-auto mb-5 text-[28px]">
              <Search className="w-7 h-7 text-white" />
            </div>
            <h3 className="feature-title font-['Orbitron'] text-xl font-semibold text-[var(--text-primary)] mb-3">
              Search Medicine Information
            </h3>
            <p className="feature-description text-[var(--text-secondary)] leading-[1.6] mb-5">
              Search for detailed medicine information including usage, dosage, side effects, and interactions from trusted medical databases
            </p>
            <button className="feature-button p-[12px_24px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] text-white border-none rounded-[10px] font-semibold cursor-pointer transition-all duration-200 hover:transform hover:-translate-y-[2px] hover:shadow-[0_8px_20px_rgba(0,212,170,0.3)]">
              Search Now
            </button>
          </div>

          <div
            id="ai-consultation-button"
            className="feature-card bg-[var(--glass-bg)] backdrop-blur-[20px] border border-[var(--glass-border)] rounded-[20px] p-8 text-center transition-all duration-300 cubic-bezier-[0.4,0,0.2,1] cursor-pointer relative overflow-hidden hover:transform hover:-translate-y-2 hover:border-[var(--primary-cyan)] hover:shadow-[0_25px_50px_rgba(0,212,170,0.2)] before:content-[''] before:absolute before:top-0 before:-left-full before:w-full before:h-full before:bg-gradient-to-r before:from-transparent before:via-[rgba(0,212,170,0.1)] before:to-transparent before:transition-[left_0.6s_ease] hover:before:left-full"
            onClick={() => handleFeatureClick('question')}
          >
            <div className="feature-icon w-[60px] h-[60px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] rounded-2xl flex items-center justify-center mx-auto mb-5 text-[28px]">
              <MessageSquare className="w-7 h-7 text-white" />
            </div>
            <h3 className="feature-title font-['Orbitron'] text-xl font-semibold text-[var(--text-primary)] mb-3">
              Ask Questions
            </h3>
            <p className="feature-description text-[var(--text-secondary)] leading-[1.6] mb-5">
              Get instant answers about medications and health
            </p>
            <button className="feature-button p-[12px_24px] bg-gradient-to-r from-[var(--primary-cyan)] to-[var(--primary-purple)] text-white border-none rounded-[10px] font-semibold cursor-pointer transition-all duration-200 hover:transform hover:-translate-y-[2px] hover:shadow-[0_8px_20px_rgba(0,212,170,0.3)]">
              Ask Now
            </button>
          </div>
        </div>

        {/* Answers Section */}
        <div id="answers-section" className="answers-section bg-[var(--glass-bg)] backdrop-blur-[20px] border border-[var(--glass-border)] rounded-[20px] p-8">
          <div className="answers-header text-center mb-8">
            <h2 className="answers-title font-['Orbitron'] text-[1.8rem] font-semibold text-[var(--text-primary)] mb-2">
              Recent Questions & Answers
            </h2>
            <p className="answers-subtitle text-[var(--text-secondary)]">
              Your latest health and medication questions
            </p>
          </div>

          <div className="answers-content max-h-[400px] overflow-y-auto py-5">
            {answers.length === 0 ? (
              <div className="no-answers text-center text-[var(--text-muted)] italic p-10">
                No questions yet. Start by asking a health or medication question.
              </div>
            ) : (
              answers.map((answer) => (
                <div key={answer.id} className="answer-item bg-[rgba(255,255,255,0.05)] rounded-xl p-5 mb-4 border-l-4 border-[var(--primary-cyan)]">
                  <div className="answer-question font-semibold text-[var(--text-primary)] mb-2">
                    Q: {answer.question}
                  </div>
                  <div className="answer-response text-[var(--text-secondary)] leading-[1.6]">
                    A: {answer.response}
                  </div>
                  <div className="answer-time text-xs text-[var(--text-muted)] mt-2">
                    {answer.timestamp.toLocaleString()}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Modal */}
      <Modal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title={modalTitle}
        type={modalType}
        onSubmit={handleAddAnswer}
      />

      {/* Interactive Tutorial */}
      {!showWelcomeModal && (
        <InteractiveTutorial
          isVisible={showTutorial}
          onComplete={handleTutorialComplete}
          onSkip={handleTutorialSkip}
        />
      )}

      {/* Welcome Modal */}
      <WelcomeModal
        isOpen={showWelcomeModal}
        onClose={handleWelcomeClose}
        onSkip={handleWelcomeSkip}
        userName={user.name}
      />
    </div>
  );
};

export default HomePage;